workflows:
  expo_android_build:
    name: Expo Android • Build AAB (download artifact)
    max_build_duration: 60
    environment:
      node: 18
      vars:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}
    cache:
      cache_paths:
        - $HOME/.npm
    scripts:
      - name: Instalar dependências
        script: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Instalar EAS CLI global
        script: npm i -g eas-cli
      - name: Conferir EAS
        script: eas --version
      - name: Build EAS (Android • production)
        script: eas build -p android --profile production --non-interactive
      - name: Baixar o AAB gerado
        script: eas build:download --latest --platform android --output app.aab
    artifacts:
      - app.aab
    publishing:
      email:
        recipients:
          - rodrigoramalhov@gmail.com

  expo_android_submit_internal:
    name: Expo Android • Build + Submit (Teste Interno)
    max_build_duration: 60
    environment:
      node: 18
      vars:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
    cache:
      cache_paths:
        - $HOME/.npm
    scripts:
      - name: Instalar dependências
        script: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Instalar EAS CLI global
        script: npm i -g eas-cli
      - name: Build EAS (Android • production)
        script: eas build -p android --profile production --non-interactive
      - name: Enviar para Google Play (track internal)
        script: eas submit -p android --latest --track internal --non-interactive
    artifacts:
      - app.aab
    publishing:
      email:
        recipients:
          - rodrigoramalhov@gmail.com
